version: '3.7'

services:
  app:
    build: './app'
    container_name: 'app'
    restart: 'always'
    ports:
      - '8000:8000'
    # expose:
    #   - '8000'
    volumes:
      - type: 'bind'
        source: './volumes/config'
        target: '/app'